version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: wallet-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      # Note: We must use the variable here too so the check succeeds
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  wallet-service:
    build: .
    container_name: wallet-app
    ports:
      - "8443:8443"
    environment:
      # Pass the profile (dev/prod)
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      
      # Inject the variables from .env
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      
      # SSL Configuration
      SERVER_SSL_KEY_STORE: file:/app/keystore.p12
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: